gluetunImage:
  repository: ghcr.io/qdm12/gluetun
  tag: latest
  pullPolicy: IfNotPresent

workload:
  main:
    podSpec:
      containers:
        gluetun:
          probes:
            liveness:
              enabled: true
              type: tcp
            startup:
              enabled: true
              type: tcp
            readiness:
              enabled: true
              type: tcp
          enabled: true
          imageSelector: gluetunImage
          env:
            TZ: "{{ .Values.TZ }}"
            VPN_TYPE: openvpn
            VPN_SERVICE_PROVIDER: private internet access
            OPENVPN_USER: aaa
            OPENVPN_PASSWORD: aaa
            FIREWALL_INPUT_PORTS: "9091"
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
service:
  gluetun:
    enabled: true
    type: ClusterIP
    ports:
      gluetun:
        enabled: true
        targetSelector: gluetun
        port: 9091
        targetPort: 9091
