gluetunImage:
  repository: ghcr.io/qdm12/gluetun
  tag: latest
  pullPolicy: IfNotPresent

workload:
  main:
    podSpec:
      containers:
        gluetun:
          probes: # TODO
            liveness:
              enabled: false
              type: tcp
              port: 8000
              path: /v1/openvpn/status
            readiness:
              enabled: false
              type: tcp
              port: 8000
              path: /v1/publicip/ip
            startup:
              enabled: false
              type: tcp
              port: 8000
              path: /v1/publicip/ip
          enabled: true
          imageSelector: gluetunImage
          env:
            VPN_TYPE: openvpn
            VPN_SERVICE_PROVIDER: pia
            #OPENVPN_USER: aaa # TODO
            #OPENVPN_PASSWORD: aaa # TODO
            FIREWALL_INPUT_PORTS: "{{ .Values.service.main.ports.main.port }}" # TODO change port on main container
          envFrom:
            - secretRef:
                name: openvpn-credentials
                expandObjectName: true
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
              drop: []
            runAsUser: 0
            runAsGroup: 0
            readOnlyRootFilesystem: false

secret:
  openvpn-credentials:
    enabled: true
    type: Opaque
    data:
      OPENVPN_USER: "{{ .Values.openvpn.username }}" # TODO
      OPENVPN_PASSWORD: "{{ .Values.openvpn.password }}" # TODO
