replicaCount: 1

service:
  type: ClusterIP
  port: 8096

ingress:
  enabled: false

persistence:
  config:
    enabled: true
    storageClass: null
    accessMode: ReadWriteOnce
    size: 1Gi
  media:
    enabled: false
  extraExistingClaimMounts:
    - name: tv-media-volume
      mountPath: /tv
      existingClaim: tv-media-volume
    - name: movies-media-volume
      mountPath: /movies
      existingClaim: movies-media-volume

# -- Larger libraries may need to increase the readinessProbe and livenessProbe timeouts. Start by increasing the initialDelaySeconds.
livenessProbe:
  enabled: true
  # failureThreshold: 3
  initialDelaySeconds: 10
  # periodSeconds: 10
  # successThreshold: 1
  # timeoutSeconds: 1

# -- Larger libraries may need to increase the readinessProbe and livenessProbe timeouts. Start by increasing the initialDelaySeconds.
readinessProbe:
  enabled: true
  # failureThreshold: 3
  initialDelaySeconds: 10
  # periodSeconds: 10
  # successThreshold: 1
  # timeoutSeconds: 1
