- name: Deploy Qbittorrent
  hosts: masters

  vars:
    service_state: present
    values_files: qbittorrent-values.yaml

  tasks:
    - name: Copy file with owner and permissions
      copy:
        src: ./k8s/helm/{{ values_files }}
        dest: /tmp/{{ values_files }}

    - name: Install Helm
      kubernetes.core.helm:
        binary_path: /snap/bin/helm
        name: qbittorrent
        chart_ref: oci://tccr.io/truecharts/qbittorrent
        release_namespace: default
        values_files:
          - /tmp/{{ values_files }}
        state: '{{ service_state }}'
