- name: Install requirements for ansible kubernetes.core role
  hosts: masters
  become: yes

  vars: {}

  tasks:
    # - name: Replace
    #   lineinfile:
    #     path: /home/vagrant/custom-resources.yaml
    #     insertafter: "^  calicoNetwork:"
    #     line: "    nodeAddressAutodetectionV4:\n      interface: eth1"
    - name: Install apt requirements
      apt:
        name: "{{ item }}"
        state: present
        # update_cache: yes
      with_items:
        - python3-pip
        # - python3-PyYAML
        - python3-kubernetes
        - python3-jsonpatch
