- name: Deploy whoami
  hosts: masters

  tasks:
    - name: Apply kubernetes configuration
      kubernetes.core.k8s:
        namespace: default
        definition: "{{ lookup('file', '{{ item }}') | from_yaml_all }}"
        state: present
      loop: "{{ q('fileglob', 'k8s/resources/*') }}"
