apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: download-media-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tv-media-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: movies-media-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
