- name: Deploy Traefik
  hosts: masters

  vars: {}

  tasks:
    - name: Copy file with owner and permissions
      copy:
        src: ./k8s/helm/traefik-values.yaml
        dest: /tmp/traefik-values.yaml

    - name: Add a Traefik repository
      kubernetes.core.helm_repository:
        binary_path: /snap/bin/helm
        repo_name: traefik
        repo_url: https://traefik.github.io/charts

    - name: Install Traefik Helm
      kubernetes.core.helm:
        binary_path: /snap/bin/helm
        name: traefik
        chart_ref: traefik/traefik
        update_repo_cache: true
        release_namespace: default
        values_files:
          - /tmp/traefik-values.yaml
        state: present
        # chart_version: v3.1.6

    - name: Apply kubernetes configuration
      kubernetes.core.k8s:
        namespace: default
        definition: "{{ lookup('file', '{{ item }}') | from_yaml_all }}"
        state: present
      loop: "{{ q('fileglob', 'k8s/resources/*') }}"
