authentik:
  log_level: trace
  secret_key: "/ImtRhs4MgA63zmhE0QInKfsyLIKiGSOx8WiZbOYf3m/1/orInvQBJK1fV9EFLOs6pPmlxJ3z37tG9FD"
  postgresql:
    password: "AoKQKTBniNUzPfV6jHGCpMJjqCYRYDtMgktzJzEQqeudFBqE25"
  error_reporting:
    enabled: false
  disable_update_check: true
  disable_startup_analytics: true

server:
  ingress:
    enabled: false

postgresql:
  enabled: true
  auth:
    password: "AoKQKTBniNUzPfV6jHGCpMJjqCYRYDtMgktzJzEQqeudFBqE25"

redis:
  enabled: true
