gluetunImage:
  repository: ghcr.io/qdm12/gluetun
  tag: latest
  pullPolicy: IfNotPresent

workload:
  main:
    podSpec:
      containers:
        gluetun:
          probes: # TODO
            liveness:
              enabled: false
              type: tcp
            startup:
              enabled: false
              type: tcp
            readiness:
              enabled: false
              type: tcp
          enabled: true
          imageSelector: gluetunImage
          env:
            VPN_TYPE: openvpn
            VPN_SERVICE_PROVIDER: pia
            #OPENVPN_USER: aaa # TODO
            #OPENVPN_PASSWORD: aaa # TODO
            FIREWALL_INPUT_PORTS: "8080" # TODO change port on main container
          envFrom:
            - secretRef:
                name: openvpn-credentials
                expandObjectName: true
          securityContext:
            capabilities:
              add: ["NET_ADMIN"]
              drop: []
            runAsUser: 0
            runAsGroup: 0
            readOnlyRootFilesystem: false

secret:
  openvpn-credentials:
    enabled: true
    type: Opaque
    data:
      OPENVPN_USER: "{{ .Values.openvpn.username }}" # TODO
      OPENVPN_PASSWORD: "{{ .Values.openvpn.password }}" # TODO
