- import_playbook: ../media-storage/playbook.yaml

- name: Deploy jellyfin
  hosts: masters

  vars:
    jellyfin_helm_version: 1.3.0
    service_state: present
    values_files: jellyfin-values.yaml

  tasks:
    - name: Copy file with owner and permissions
      copy:
        src: ./k8s/helm/{{ values_files }}
        dest: /tmp/{{ values_files }}

    - name: Install Helm
      kubernetes.core.helm:
        binary_path: /snap/bin/helm
        name: jellyfin
        chart_ref: https://github.com/jellyfin/jellyfin-helm/releases/download/jellyfin-{{ jellyfin_helm_version }}/jellyfin-{{ jellyfin_helm_version }}.tgz
        release_namespace: default
        values_files:
          - /tmp/{{ values_files }}
        state: '{{ service_state }}'
