- import_playbook: ../media-storage/playbook.yaml

- name: Deploy jellyfin
  hosts: masters

  vars:
    jellyfin_helm_version: 1.3.0
    service_state: present

  tasks:
    - name: Copy file with owner and permissions
      copy:
        src: ./k8s/helm/jellyfin-values.yaml
        dest: /tmp/jellyfin-values.yaml

    - name: Install Jellyfin Helm
      kubernetes.core.helm:
        binary_path: /snap/bin/helm
        name: jellyfin
        chart_ref: https://github.com/jellyfin/jellyfin-helm/releases/download/jellyfin-{{ jellyfin_helm_version }}/jellyfin-{{ jellyfin_helm_version }}.tgz
        release_namespace: default
        values_files:
          - /tmp/jellyfin-values.yaml
        state: '{{ service_state }}'
