- name: Deploy proxy namespace
  hosts: masters
  become: yes

  vars: {}

  tasks:
    - name: Install nginx
      kubernetes.core.k8s:
        namespace: default
        definition: "{{ lookup('file', '{{ item }}') | from_yaml }}"
        state: present
      with_items:
        - ./traefik.account.yml
        - ./traefik.deployment.yml
        - ./traefik.role.yml
        - ./traefik.rolebinding.yml
        - ./traefik.service.yml
        - ./traefik-dashboard.service.yml
