apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: download-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
