- name: Deploy Authentik
  hosts: masters

  vars: {}

  tasks:
    - name: Copy file with owner and permissions
      copy:
        src: ./k8s/helm/authentik-values.yaml
        dest: /tmp/authentik-values.yaml

    - name: Add a Authentik repository
      kubernetes.core.helm_repository:
        binary_path: /snap/bin/helm
        repo_name: authentik
        repo_url: https://charts.goauthentik.io

    - name: Install Authentik Helm
      kubernetes.core.helm:
        binary_path: /snap/bin/helm
        name: authentik
        chart_ref: authentik/authentik
        update_repo_cache: true
        release_namespace: default
        values_files:
          - /tmp/authentik-values.yaml
        state: present
        # chart_version: 2024.8.3
