- name: Deploy Sonarr
  hosts: masters

  vars:
    service_state: present
    values_files: sonarr-values.yaml
    tc_name: sonarr

  tasks:
    - name: Copy file with owner and permissions
      copy:
        src: ./k8s/helm/{{ values_files }}
        dest: /tmp/{{ values_files }}

    - name: Install Helm
      kubernetes.core.helm:
        binary_path: /snap/bin/helm
        name: '{{ tc_name }}'
        chart_ref: oci://tccr.io/truecharts/{{ tc_name }}
        release_namespace: default
        values_files:
          - /tmp/{{ values_files }}
        state: '{{ service_state }}'
