apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: authentik
  namespace: default
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`auth.server`)
      kind: Rule
      services:
        - name: authentik-server
          port: 80
