apiVersion: apps/v1
kind: Deployment
metadata:
  name: jellyfin
  namespace: default
  labels:
    app: jellyfin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyfin
  template:
    metadata:
      labels:
        app: jellyfin
    spec:
      containers:
        - name: jellyfin
          image: jellyfin/jellyfin
          envFrom:
            - configMapRef:
                name: jellyfin-config
          imagePullPolicy: Always
          readinessProbe:
            tcpSocket:
              port: 8096
            initialDelaySeconds: 10
            periodSeconds: 10
          ports:
            - containerPort: 8096
              name: http
              protocol: TCP
          resources:
            limits:
              cpu: 2000m
              memory: 2Gi
            requests:
              cpu: 1000m
              memory: 2Gi
